test: 
	cd ipr-shapes && $(MAKE) all
	cd labels && $(MAKE) all
	cd styles && $(MAKE) all
	cd values-test && $(MAKE) all
	cd variables && $(MAKE) all
	cd combine && $(MAKE) all
	cd combine2 && $(MAKE) all
